services:
  - type: web
    name: ventas-api-gateway
    runtime: docker
    rootDir: ./microservices/api-gateway
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: AUTH_SERVICE_URL
        value: https://ventas-auth-service.onrender.com
      - key: PRODUCT_SERVICE_URL
        value: https://ventas-product-service.onrender.com
      - key: ORDER_SERVICE_URL
        value: https://ventas-order-service.onrender.com

  - type: web
    name: ventas-auth-service
    runtime: docker
    rootDir: ./microservices/auth-service
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-fragrant-wildflower-avy022de-pooler.c-11.us-east-1.aws.neon.tech/ventas_auth?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_ndbiWmqBL14a
      - key: JWT_SECRET
        value: ventasPlatformSecretKeyThatIsLongEnoughForHMACSHA256Algorithm2024

  - type: web
    name: ventas-product-service
    runtime: docker
    rootDir: ./microservices/product-service
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-fragrant-wildflower-avy022de-pooler.c-11.us-east-1.aws.neon.tech/ventas_products?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_ndbiWmqBL14a
      - key: KAFKA_ENABLED
        value: "false"

  - type: web
    name: ventas-order-service
    runtime: docker
    rootDir: ./microservices/order-service
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /actuator/health
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://ep-fragrant-wildflower-avy022de-pooler.c-11.us-east-1.aws.neon.tech/ventas_orders?sslmode=require
      - key: SPRING_DATASOURCE_USERNAME
        value: neondb_owner
      - key: SPRING_DATASOURCE_PASSWORD
        value: npg_ndbiWmqBL14a
      - key: PRODUCT_SERVICE_URL
        value: https://ventas-product-service.onrender.com
      - key: KAFKA_ENABLED
        value: "false"
